---
#Chequeo las dos interfaces que tengo tanto en Ubuntu como en Rocky

- hosts: linux
  remote_user: ansible
  become: yes
  become_method: sudo

  tasks:

  - name: Ver interfaces de Red 
    debug:
      msg: "LIsta de interfaces de red: {{ ansible_interfaces }}"
